<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "phipfels_watchword"
 *
 * Auto generated by Extension Builder 2015-04-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Herrnhuter Losung',
	'description' => 'Contains the current watchword from the Herrnhuter Brüdergemeine / Losungen',
	'category' => 'plugin',
	'author' => 'Philipp Schumann',
	'author_email' => 'ph.schumann@gmx.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.0.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);